#!/bin/bash

# This script adds the V1 logos, and names to the configs.

opt_set STRING_CONFIG_H_AUTHOR "\"(Rudebrew22, ${V1_VERSION})\""

# opt_set won't work, because it isn't in the configuration or configuration_adv.h, so I'm going to
# just put it into the Configuration.h

echo "#define SHORT_BUILD_VERSION \"${V1_VERSION} ${MARLIN_VERSION}\"" >> Marlin/Configuration.h

opt_enable \
    DIRECT_PIN_CONTROL \
    EEPROM_AUTO_INIT

opt_disable \
EVENT_GCODE_SD_ABORT

#https://www.reddit.com/r/MarlinFirmware/comments/f1rysl/bootscreens_in_20/
#cp $CFGDIR/common/_Bootscreen.h Marlin/
#opt_enable SHOW_CUSTOM_BOOTSCREEN #You have enabled SHOW_CUSTOM_BOOTSCREEN and CUSTOM_STATUS_SCREEN_IMAGE but you have not copied over or created the the required _Bootscreen.h and _Statusscreen.h
#opt_disable SHOW_CUSTOM_BOOTSCREEN

# Start by putting the machine config and the marlin version in the readme
echo "# ${CONFIG_NAME} - ${MARLIN_VERSION} - ${V1_VERSION}" > README.md
cat $CFGDIR/common/Readme_header.md >> README.md
